name: dev-check-repository

on: [push]

jobs:
  build-node-test:
    runs-on: ubuntu-latest

    container:
      image: opendigitaleducation/node:18-alpine-pnpm
      options: --user root -v ${{ github.workspace }}:/home/node/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run pnpm install
        working-directory: ./frontend
        run: pnpm install
      - name: Check Quality Code
        working-directory: ./frontend
        run: pnpm run format:check && pnpm run lint
      - name: Run Build Vite
        working-directory: ./frontend
        run: pnpm build
      - name: Run tests
        working-directory: ./frontend
        run: pnpm test

  build-maven-test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.6-jdk-8
      options: --user root -v ${{ github.workspace }}:/home/maven/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run build maven
        working-directory: ./backend
        run: mvn -Duser.home=/var/maven clean install
      - name: Run maven test
        working-directory: ./backend
        run: mvn -Duser.home=/var/maven test